before_script:
- whoami
- ./devops/ci/scripts/check-free-space.sh

variables:
  packageName: MODULE_NAME
  GITLAB_TOKEN: $GITLAB_TOKEN
  NPM_TOKEN: $NPM_TOKEN

stages:
- lint
- test
- build
- publish
- docs

lint:
  stage: lint
  except:
    variables:
    - $CI_COMMIT_TAG =~ /.+/
    - $CI_COMMIT_MESSAGE =~ /\d+\.\d+\.\d+/
  script:
  - ./devops/ci/scripts/lint.job.sh

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
  - lint
  except:
    variables:
    - $CI_COMMIT_TAG =~ /.+/
    - $CI_COMMIT_MESSAGE =~ /\d+\.\d+\.\d+/
  script:
  - ./devops/ci/scripts/test.job.sh
  artifacts:
    paths:
    - coverage/
    expire_in: 1h

build:
  stage: build
  except:
    variables:
    - $CI_COMMIT_TAG =~ /.+/
    - $CI_COMMIT_MESSAGE =~ /\d+\.\d+\.\d+/
  script:
  - ./devops/ci/scripts/build.job.sh
  artifacts:
    paths:
    - dist/
    expire_in: 1h

publish:
  stage: publish
  dependencies:
    - build
  only:
    - master
  before_script:
    - npm i --quiet semantic-release
  script:
    - npm run release


pages:
  stage: docs
  dependencies:
  - test
  script:
  - mkdir public
  - cp -r docs/. public
  artifacts:
    paths:
    - public
    expire_in: 30 days
  only:
  - semantic-relase
  except:
    variables:
    - $CI_COMMIT_TAG =~ /.+/
    - $CI_COMMIT_MESSAGE =~ /\d+\.\d+\.\d+/
