image: node:12-alpine

variables:
  GITLAB_TOKEN: $GITLAB_TOKEN
  NPM_TOKEN: $NPM_TOKEN

stages:
- install
- check
- build
- release
- docs

install:
  stage: install
  tags:
    - internal-docker
  artifacts:
    expire_in: 1h
    paths:
      - node_modules
  before_script:
    - npm cache clean --force
  script:
    - npm ci --quiet


lint:
  stage: check
  tags:
    - internal-docker
  dependencies:
    - install
  script:
    - npm run lint


test:
  stage: check
  dependencies:
    - install
  artifacts:
    expire_in: 1h
    paths:
      - coverage/
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - npm run test:coverage


build:
  stage: build
  tags:
    - internal-docker
  dependencies:
    - install
  script:
    - npm run build


release:
  image: node:12
  stage: release
  tags:
    - internal-docker
  dependencies:
    - install
  only:
    - master
  script:
    - npm run release


pages:
  image: alpine:3.7
  stage: docs
  tags:
    - internal-docker
  only:
    - master
  artifacts:
    paths:
      - public
  script:
    - mkdir public
    - cp -r docs/. public
