language: node_js
node_js: "10"

env:
  - GITHUB_TOKEN: $GITHUB_TOKEN

intall: true
script: true

addons:
  sonarcloud:
    organization: ciklum-digital
    token:
      secure: $SONAR_TOKEN

stages:
  - test
  - release

jobs:
  include:
    - stage: "test"
      name: "linting | testing | building"
      script:
        - npm run lint
        - npm run test:ci
        - sonar-scanner
        - npm run build
    - stage: "release"
      if: branch = master
      script: npm run release
