language: node_js
node_js: "10"

env:
  - GITHUB_TOKEN: $GITHUB_TOKEN

before_install: npm cache clean --force
install: npm ci --quiet

before_script:
  - npm run lint
  - npm test

script: npm run build

stages:
  - name: release
    if: branch = travis

jobs:
  include:
    - stage: "release"
      name: "npm release"
      script: npm run release









#notifications:
#  slack:
#    on_success: change
#    on_failure: always
#    rooms:
#      # Generate with
#      #     travis encrypt "babeljs:<token>#activity" --add notifications.slack.rooms
#      # where <token> is from the Slack integration settings.
#      secure: SrwPKRe2AiNAKRo/+2yW/x4zxbWf2FBXuBuuPkdTJVTpWe++Jin1lXYJWTKP1a1i/IbmhffBO9YZcUFbeuXJpRM083vO8VYpyuBMQRqWD+Z3o+ttPlHGOJgnj0nkIcGRk6k7PpyHNnIkixfEJDvbbg9lN1Jswb3xkL8iYIHpuFE=

#  - if [[ $TRAVIS_BRANCH == "travis" ]]; then npm run release; fi

#stages:
#  - check
#  - build
#  - name: release
#    if: branch = travis
#
#jobs:
#  include:
#    - stage: "check"
#    - name: "lint"
#      script: npm run lint
#    - name: "unit tests"
#      script: npm test
#    - stage: build
#      name: "build artifacts"
#      script: npm run build
#    - stage: "release"
#      name: "npm release"
#      script: npm run release
