language: node_js
node_js: "10"

env:
  - GITHUB_TOKEN: $GITHUB_TOKEN

intall: true
script: true

stages:
  - test
  - release

jobs:
  include:
    - stage: "test"
      name: "linting | testing | building"
      script:
        - npm run lint
        - npm run ci:test
        - npm run build
    - stage: "release"
      if: branch = travis
      script: npm run release



# # option 3
#install: npm ci --quiet

#script:
#  - npm run lint
#  - npm run ci:test
#  - npm run build
#  - if [[ $TRAVIS_BRANCH == "travis" ]]; then npm run release; fi
