language: node_js
node_js: "10"

install:
  - npm ci

addons:
  sonarcloud:
    organization: ciklum-digital
    token:
      secure: $SONAR_TOKEN

script:
  - npm run lint
  - npm run test:ci
  - sonar-scanner
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    branch: master


#env:
#  - GITHUB_TOKEN: $GITHUB_TOKEN
#
#intall: true
#script: true
#
#stages:
#  - test
#  - release
#
#jobs:
#  include:
#    - stage: "test"
#      name: "linting | testing | building"
#      script:
#        - npm run lint
#        - npm run test:ci
#        - npm run build
#    - stage: "release"
#      if: branch = master
#      script: npm run release
