language: node_js
node_js: "10"
cache: npm

env:
  - GITHUB_TOKEN: $GITHUB_TOKEN

before_install: npm cache clean --force
install: npm ci --quiet

script:
  - npm run lint
  - npm test
  - npm run build
  - if [ $TRAVIS_BRANCH == "travis"]; then npm run release fi

#stages:
#  - check
#  - build
#  - name: release
#    if: branch = travis
#
#jobs:
#  include:
#    - stage: "check"
#    - name: "lint"
#      script: npm run lint
#    - name: "unit tests"
#      script: npm test
#    - stage: build
#      name: "build artifacts"
#      script: npm run build
#    - stage: "release"
#      name: "npm release"
#      script: npm run release
