language: node_js
node_js: "10"

env:
  - GITHUB_TOKEN: $GITHUB_TOKEN

install: npm ci --quiet

#script:
#  - npm run lint
#  - npm run ci:test
#  - npm run build
#  - if [[ $TRAVIS_BRANCH == "travis" ]]; then npm run release; fi
script: true

stages:
  - test
  - name: release
    if: branch = travis

jobs:
  include:
    - stage: "test"
    - name: "linting"
      script: npm run lint
    - name: "unit testing"
      script: npm run ci:test
    - name: "building"
      script: npm run build
    - stage: "release"
      name: "releasing"
      script: npm run release



#notifications:
#  slack:
#    on_success: change
#    on_failure: always
#    rooms:
#      # Generate with
#      #     travis encrypt "babeljs:<token>#activity" --add notifications.slack.rooms
#      # where <token> is from the Slack integration settings.
#      secure: SrwPKRe2AiNAKRo/+2yW/x4zxbWf2FBXuBuuPkdTJVTpWe++Jin1lXYJWTKP1a1i/IbmhffBO9YZcUFbeuXJpRM083vO8VYpyuBMQRqWD+Z3o+ttPlHGOJgnj0nkIcGRk6k7PpyHNnIkixfEJDvbbg9lN1Jswb3xkL8iYIHpuFE=
# https://github.com/juliuscc/semantic-release-slack-bot
#  - if [[ $TRAVIS_BRANCH == "travis" ]]; then npm run release; fi

#stages:
#  - test
#  - name: release
#    if: branch = travis
#
#jobs:
#  include:
#    - stage: "test"
#    - name: "lint"
#      script: npm run lint
#    - name: "test"
#      script: npm test
#    - name: "build"
#      script: npm run build
#    - stage: "release"
#      name: "release"
#      script: npm run release
