language: node_js
node_js: "10"
cache: npm

before_install:
  - npm cache clean --force
install:
  - npm ci --quiet

stages:
  - check
  - build
  - name: release
    if: branch = travis

jobs:
  include:
    - stage: "check"
      name: "lint:check"
      script: npm run lint
    - script: npm test
      name: "test:check"
    - stage: build
      name: "dist:build"
      script: npm run build
    - stage: "release"
      name: "npm:release"
      script: npm run release
